# Welcome to Jekyll!!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `bundle exec jekyll serve`. If you change this file. Please restart the server process.
#
# If you need help with YAML syntax, here are some quick reference for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.como/docs/yaml/
#

#───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
# Site settings:
#───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
# There are used to personalize you new site. If you look in the HTML files,
# you will see time accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}

# The release of Jekyll now that you're using
version: v2.0.0

title: InCyVerse
name: InCyVerse
email: incyverse@gmail.com
description: >- # this means to ignore newlines until "baseurl:"

language: "en-US"

# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#CNAME: blog.incyverse.com # add cname for website to be created

# Blog logo image URL, recommended size cannot exceed 300px * 300px
#logo: assets/images/logo.png
#logo_dark: assets/images/logo-dark.png
logo: ""

# Favicon (appears in browser tab) image URL, preferably smaller (64px * 64px) image.
#favicon: assets/images/favicon.png
favicon: ""

#cover: assets/images/cover.jpg
#avatar: assets/images/logo.jpg

#navigation: True
navigation:
  - name: Home
    url: /
  - name: About
    url: /about
  - name: Archive
    url: /archive
  - name: Tags
    url: /tags

paginate: 10

# If 'True' the submit button is disabled for now, but you can change that
# by editing `_includes/subscribe-form.html`
#subscribers: True # You need to connect an external service for this to work.

#words_per_minute: 200

#google_analytics: UA-69281367-1

#disqus: jekyll # shortname
#disqus_shortname: jekyll

# If 'True' the submit button is disabled for now, but you can change that by editing `_includes/subscribe-form.html'
github: incyverse
facebook: ""
twitter: ""

#footer-links:
#  behance: # https://www.behance.net/<>
#  dribbble: # https://dribbble.com/<>
#  email: fromendworld@outlook.com
#  facebook: #https://www.facebook.com/<>
#  flickr: #https://www.flickr.com/<>
#  github: FromEndWorld/loffer #https://github.com/<>
#  instagram: #https://instagram.com/<>
#  linkedin: #https://www.linkedin.com/in/<>
#  pinterest: #https://www.pinterest.com/<>
#  rss: #随便填点啥RSS就能用了
#  stackoverflow: # http://stackoverflow.com/<>
#  tumblr: # https://<username>.tumblr.com
#  twitter: # https://www.twitter.com/<your_twitter_username>
#  weibo: frommidworld #请输入你的微博个性域名 https://www.weibo.com/<thispart>
#  youtube: # channel/<your_long_string> or user/<user-name>

#───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
# Default YAML values:
#───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
#defaults:
#  -
#    scope:
#      path: ""
#      type: "posts"

# Authors' info in `_data/authors.yml`
# Tag' info in `_data/tags_info.yml`

#───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
# Jekyll configuration:
#───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
feed:
  path: feed.xml

highlighter: rouge

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: "highlight"

markdown: kramdown

paginate_path: /page:num

#permalink: /author/:author
#permalink: /tag/:tag
permalink: /:title

# Use the following plug-ins
#plugins_dir: [_plugins] # takes an array of strings and loads plugin in that order
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Set the SASS partials directory, as we're using @imports
sass:
  sass_dir: _sass
  style: expanded # You might prefer to minify using :compressed

timezone: Asia/Seoul

#───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
# Exclude from processing:
#───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
# The following items will not be processed. by default.
# Any item listed under the `exclude:` key here will be automatically added to the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `included:` list.
exclude:
  - assets/css
  - node_modules
  - vendor
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - LICENSE
  - CNAME
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
  - script.py
  - changelog.md
  - "*.Rmd"
  - .git*
  - .sass-cache
  - .jekyll-cache

excerpt_separator: ---
