# Welcome to Jekyll!!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `bundle exec jekyll server`. If you change this file. please restart the server process.
#
# If you need help with YAML syntax, here are some quick reference for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.como/docs/yaml/

#───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
# Site settings:
#───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
# There are used to personalize you new site. If you look in the HTML files,
# you will see time accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}

#title: InCyVerse
name: InCyVerse
#email: incyverse@gmail.com
description: >- # this means to ignore newlines until "baseurl:"

# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#CNAME: blog.incyverse.com # add cname for website to be created

#logo: assets/images/logo.png
# Favicon (appears in browser tab) image URL, preferably smaller (64px * 64px) image.
favicon: assets/images/favicon.png
#cover: assets/images/cover.jpg
# Blog logo image URL, recommended size cannot exceed 300px * 300px
avatar: assets/images/logo.png

# If 'True' the submit button is disabled for now, but you can change that by editing `_includes/subscribe-form.html`
#github: incyverse
#facebook:
#twitter:

#───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
# Jekyll configuration:
#───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
#highlighter: rouge

#language: "en-US"

#markdown: kramdown
# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: "highlight"

navigation:
  - name: Home
    url: /
  - name: About
    url: /about
  - name: Archive
    url: /archive
  - name: Tags
    url: /tags

paginate: 10
paginate_path: /page:num/

#permalink: /author/:author
#permalink: /tag/:tag
permalink: /:title/

#subscribers: True # You need to connect an external service for this to work.

#timezone: Asia/Seoul

version: v2.0.0 # The release of Jekyll now that you're using

#words_per_minute: 200

# Analytics
#google_analytics: UA-69281367-1 # Replace with your GA tracking identifier

# Comment
#disqus: loffer #shortname
#disqus_shortname: jekyllt # replace with your disqus username

footer-links:
#  behance: # https://www.behance.net/<>
#  dribbble: # https://dribbble.com/<>
#  email: fromendworld@outlook.com
#  facebook: #https://www.facebook.com/<>
#  flickr: #https://www.flickr.com/<>
#  github: FromEndWorld/loffer #https://github.com/<>
#  instagram: #https://instagram.com/<>
#  linkedin: #https://www.linkedin.com/in/<>
#  pinterest: #https://www.pinterest.com/<>
#  rss: #随便填点啥RSS就能用了
#  stackoverflow: # http://stackoverflow.com/<>
#  tumblr: # https://<username>.tumblr.com
#  twitter: # https://www.twitter.com/<your_twitter_username>
#  weibo: frommidworld #请输入你的微博个性域名 https://www.weibo.com/<thispart>
#  youtube: # channel/<your_long_string> or user/<user-name>

footer-text: Copyright (c) 2020

#───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
# Build settings:
#───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
#plugins_dir: [_plugins]
# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Set the SASS partials directory, as we're using @imports
sass:
  sass_dir: _sass
  style: :expanded # You might prefer to minify using :compressed

#feed:
#  path: feed.xml

#───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
# Default YAML values:
#───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
#defaults:
#  -
#    scope:
#      path: ""
#      type: "posts"

#───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
# Exclude from processing:
#───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
# The following items will not be processed. by default.
# Any item listed under the `exclude:` key here will be automatically added to the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `included:` list.
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
#  - .jekyll-cache
#  - .sass-cache
#  - node_modules
#  - vendor

excerpt_separator: ---
