# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values which you are expected to set up once and
# rarely edit after that. If you find yourself editing this file very often, consider using Jekyll's data files feature
# for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use `bundle exec jekyll serve`. If you
# change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
# themes: loffer, jasper2

#───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
# SITE SETTINGS:
#───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
# These are used to personalize your new site. If you look in the HTML files, you will see them accessed via
# {{ site.title }}, {{ site.email }}, and so on. You can create any custom variable you would like, and they will be
# accessible in the templates via {{ site.myvariable }}.

# The release of Jekyll now that you're using
version: 2.0.0
language: "en"
timezone: Asia/Seoul
excerpt_separator: ---

title: InCyVerse
name: InCyVerse
email: incyverse@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  10,000 Hours...

# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: / # the subpath of your site, e.g. /blog
url: # the base hostanme & protocol for your site, e.g. http://example.com
CNAME: # add cname for website to be created

# Blog logo image URL, recommended size cannot exceed 300px * 300px
#logo: assets/images/icon.png
#logo_dark: assets/images/favicon.png

# Favicon (appears in browser tab) image URL, preferably smaller 64px * 64px image
#favicon: assets/images/favicon.png

#cover: assets/images/cover.jpg
#avatar: assets/images/avatar.jpg

navigation: true # show the navbar links
paginate: 100 # it will paginate after this number
paginate_path: /page:num

# If 'true' the submit button is disabled for now, but you can change that by editing `_includes/subscribe-form.html`
subscribers: true # you need to connect an external service fot this to work

words_per_minute: 200

#disqus: false
#disqus_shortname: jekyllt # replace with your disqus username

github: incyverse
facebook: incyverse

footer-links:
  behance: "" # https://www.behance.net/USERNAME
  dribbble: "" # https://dribbble.com/USERNAME
  email: incyverse@gmail.com
  facebook: https://www.facebook.com/incyverse
  flickr: "" # https://www.flickr.com/USERNAME
  github: https://github.com/USERNAME
  instagram: "" # https://instagram.com/USERNAME
  linkedin: "" # https://www.linkedin.com/in/USERNAME
  pinterest: "" # https://www.pinterest.com/USERNAME
  stackoverflow: # https://stackoverflow.com/USERNAME
  tumblr: "" # https://USERNAME.tumblr.com
  twitter: "" # https://www.twitter.com/USERNAME
  weibo: "" # https://www.weibo.com/USERNAME
  youtube: "" # channel/<YOUR LONG STRING> or user/USERNAME

#google_analytics: UA-69281367-1 # replace with your GA tracking identifier

#───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
# BUILD SETTINGS:
#───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
# gems and other configs
#plugins_dir: [_plugins]
plugins:
  - jekyll-feed
#  - jekyll-paginate

defaults:
  -
    scope:
      path: ""
      type: "posts"

#permalink: /:title
# Authors info in `_data/authors.yml`
#permalink: /author/:author
# Tags info in `_data/tags_info.yml`
#permalink: /tag/:tag

markdown: kramdown
highlighter: rouge

feed:
  path: feed.xml

sass:
  style: :expanded # You might prefer to minify using :compressed

#───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
# JEKYLL CONFIGURATION:
#───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
jekyll_compose:
  default_front_matter:
    posts:
      description:
      categories:
      tags:
      image:
        path:
        alt:
      pin: false
      math: true
      mermaid: true

#───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
# DEPLOY SETTINGS:
#───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
# Username and repo of github repo, e.g. https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis repo defaults to USERNAME.github.io
# Branch defaults to 'source' for USERNAME.github.io or 'main' otherwise
#safe: false
#lsi: false
#username: jekyllt
#repo: incyverse
#branch: main
#relative_source: ../incyverse/
#destination: ../incyverse-pages/
#production_url: https://jekyllt.github.io/incyverse/
#source_url: https://github.com/jekyllt/incyverse/

#───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
# EXCLUDE FROM PROCESSING:
#───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
# The following items will not be processed, by default. Any item listed under the `exclude:` key here will be
# automatically added to the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or their entries file path in the `include:` list.
exclude:
  - assets/css
  - node_modules
  - vendor
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - LICENSE
  - CNAME
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
  - script.py
  - changelog.md
  - "*.Rmd"
  - .git*
  - .sass-cache
  - .jekyll-cache
#  - gemfiles/
#  - vendor/bundle/
#  - vendor/cache/
#  - vendor/gems/
#  - vendor/ruby/
